# Core bot functionality
bot-core:
  - src/main/java/edu/moravian/BotResponder.java
  - src/main/java/edu/moravian/BotResponses.java
  - src/main/java/edu/moravian/TorkBot.java

# Storage and session management
storage:
  - src/main/java/edu/moravian/MemoryStorage.java
  - src/main/java/edu/moravian/RedisManager.java
  - src/main/java/edu/moravian/QuestionStorage.java
  - src/main/java/edu/moravian/SessionManager.java

# Question handling
questions:
  - src/main/java/edu/moravian/MultipleChoiceQuestion.java
  - src/main/java/edu/moravian/QuestionLoader.java
  - src/main/java/edu/moravian/QuestionManager.java

# Error handling and exceptions
exceptions:
  - src/main/java/edu/moravian/exceptions/**/*

# Documentation
documentation:
  - '**/*.md'
  - TeamWorkBotUML.png

# Tests
tests:
  - src/test/**/*

# Build configuration
build:
  - pom.xml
  - startbot.sh

# Docker configuration
docker:
  - Docker/**/*
  - Dockerfile
