version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Docker/Dockerfile  # <--- since your Dockerfile is inside /Docker
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always