version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - redis_network
        
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
