name: Checkstyle Tests
on:
  push: 
    branches: 
      - main
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK (Java 21)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Run Checkstyle checks
      - name: Run Checkstyle
        run: mvn checkstyle:check
            
            
    
