name: checkstyle
on:
  push:
    branches:
      - main
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK (Java 21)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Ensure custom style checks are used
      - name: Ensure custom checkstyle.xml is used
        run: |
          if [ ! -f checkstyle.xml ]; then
          echo "Error: checkstyle.xml not found in the repository root."
          exit 1
          fi

      # Run Checkstyle
      - name: Checkstyle Check
        run: mvn checkstyle:check