name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy and Run Script on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #!/bin/bash
            yum install git -y
            yum install redis6 -y
            yum install docker -y
            yum install -y maven-amazon-corretto21
            git clone https://github.com/cs220s25/Anthony-Matt-Mael.git 
            cd Anthony-Matt-Mael
            systemctl enable redis6
            systemctl start redis6
            mvn clean package
            java -jar target/dbot-1.0-SNAPSHOT.jar
