name: Discord Bot Build and Package

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: discord-bot-jar
        path: target/dbot-*.jar
        
    # Optional: Only publish to GitHub Packages on release branches or tags
    - name: Publish to GitHub Packages
      if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${GITHUB_ACTOR}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
