name: Docker Compose Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: |
          docker-compose -f .github/workflows/docker-compose.yml up -d --build

      - name: List running containers
        run: docker ps