name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.PERSONAL_TOKEN }}"
        configuration-path: ".github/labeler.yml"
        sync-labels: true
